platform :ios, '8.0'
use_frameworks!
pod 'AFNetworking', '~> 2.5'
pod 'JSONModel'
pod 'SVPullToRefresh'
pod 'SDWebImage', '~>3.7'
pod 'TLYShyNavBar'
pod 'MNColorKit'
pod 'Fabric'
pod 'Crashlytics'
pod 'Flurry-iOS-SDK/FlurrySDK'
pod 'ReactiveCocoa'
