source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
pod 'AFNetworking', '~> 3.0'
pod 'JSONModel'
pod 'SDWebImage', '~>3.7'
#pod 'SVPullToRefresh'
#pod 'SDWebImage', '~>3.7'
#pod 'TLYShyNavBar'
#pod 'MNColorKit'
